package com.startup.entity;
// Generated Mar 26, 2016 2:04:24 PM by Hibernate Tools 5.1.0.Alpha1


import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.startup.helper.JsonToPointDeserializer;
import com.startup.helper.PointToJsonSerializer;
import com.vividsolutions.jts.geom.Geometry;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AirportsUs generated by hbm2java
 */
@Entity
@Table(name="airports_us"
    ,schema="public"
)
public class AirportsUs implements Serializable {

     private int id;
     private Geometry geom;
     private Long airprtx010;
     private String feature;
     private String icao;
     private String iata;
     private String airptName;
     private String city;
     private String state;
     private String stateFips;
     private String county;
     private String fips;
     private Long totEnp;
     private Double latitude;
     private Double longitude;
     private Double elev;
     private String actDate;
     private String cntlTwr;

    public AirportsUs() {
    }

	
    public AirportsUs(int id) {
        this.id = id;
    }
    public AirportsUs(int id, Geometry geom, Long airprtx010, String feature, String icao, String iata, String airptName, String city, String state, String stateFips, String county, String fips, Long totEnp, Double latitude, Double longitude, Double elev, String actDate, String cntlTwr) {
       this.id = id;
       this.geom = geom;
       this.airprtx010 = airprtx010;
       this.feature = feature;
       this.icao = icao;
       this.iata = iata;
       this.airptName = airptName;
       this.city = city;
       this.state = state;
       this.stateFips = stateFips;
       this.county = county;
       this.fips = fips;
       this.totEnp = totEnp;
       this.latitude = latitude;
       this.longitude = longitude;
       this.elev = elev;
       this.actDate = actDate;
       this.cntlTwr = cntlTwr;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="geom")
    public Geometry getGeom() {
        return this.geom;
    }
    
    public void setGeom(Geometry geom) {
        this.geom = geom;
    }

    
    @Column(name="airprtx010")
    public Long getAirprtx010() {
        return this.airprtx010;
    }
    
    public void setAirprtx010(Long airprtx010) {
        this.airprtx010 = airprtx010;
    }

    
    @Column(name="feature", length=10)
    public String getFeature() {
        return this.feature;
    }
    
    public void setFeature(String feature) {
        this.feature = feature;
    }

    
    @Column(name="icao", length=10)
    public String getIcao() {
        return this.icao;
    }
    
    public void setIcao(String icao) {
        this.icao = icao;
    }

    
    @Column(name="iata", length=10)
    public String getIata() {
        return this.iata;
    }
    
    public void setIata(String iata) {
        this.iata = iata;
    }

    
    @Column(name="airpt_name", length=254)
    public String getAirptName() {
        return this.airptName;
    }
    
    public void setAirptName(String airptName) {
        this.airptName = airptName;
    }

    
    @Column(name="city", length=254)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="state", length=5)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="state_fips", length=5)
    public String getStateFips() {
        return this.stateFips;
    }
    
    public void setStateFips(String stateFips) {
        this.stateFips = stateFips;
    }

    
    @Column(name="county", length=254)
    public String getCounty() {
        return this.county;
    }
    
    public void setCounty(String county) {
        this.county = county;
    }

    
    @Column(name="fips", length=5)
    public String getFips() {
        return this.fips;
    }
    
    public void setFips(String fips) {
        this.fips = fips;
    }

    
    @Column(name="tot_enp")
    public Long getTotEnp() {
        return this.totEnp;
    }
    
    public void setTotEnp(Long totEnp) {
        this.totEnp = totEnp;
    }

    
    @Column(name="latitude", precision=17, scale=17)
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="longitude", precision=17, scale=17)
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="elev", precision=17, scale=17)
    public Double getElev() {
        return this.elev;
    }
    
    public void setElev(Double elev) {
        this.elev = elev;
    }

    
    @Column(name="act_date", length=10)
    public String getActDate() {
        return this.actDate;
    }
    
    public void setActDate(String actDate) {
        this.actDate = actDate;
    }

    
    @Column(name="cntl_twr", length=5)
    public String getCntlTwr() {
        return this.cntlTwr;
    }
    
    public void setCntlTwr(String cntlTwr) {
        this.cntlTwr = cntlTwr;
    }




}


