package com.startup.entity;
// Generated Mar 26, 2016 2:04:24 PM by Hibernate Tools 5.1.0.Alpha1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rainfall generated by hbm2java
 */
@Entity
@Table(name="rainfall"
    ,schema="public"
)
public class Rainfall  implements java.io.Serializable {


     private long id;
     private Serializable geom;
     private Long gridcode;

    public Rainfall() {
    }

	
    public Rainfall(long id) {
        this.id = id;
    }
    public Rainfall(long id, Serializable geom, Long gridcode) {
       this.id = id;
       this.geom = geom;
       this.gridcode = gridcode;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="geom")
    public Serializable getGeom() {
        return this.geom;
    }
    
    public void setGeom(Serializable geom) {
        this.geom = geom;
    }

    
    @Column(name="gridcode")
    public Long getGridcode() {
        return this.gridcode;
    }
    
    public void setGridcode(Long gridcode) {
        this.gridcode = gridcode;
    }




}


