package com.startup.entity;
// Generated Mar 30, 2016 6:04:58 PM by Hibernate Tools 5.1.0.Alpha1

import com.vividsolutions.jts.geom.Geometry;

import javax.persistence.*;

/**
 * SolarRadiationLatilt generated by hbm2java
 */
@Entity
@Table(name="solar_radiation_latilt"
    ,schema="public"
)
public class SolarRadiationLatilt implements java.io.Serializable, BaseEntity {

     private long id;
     private Geometry geom;
     private Long gridcode;
     private Double jan;
     private Double feb;
     private Double mar;
     private Double apr;
     private Double may;
     private Double jun;
     private Double jul;
     private Double aug;
     private Double sep;
     private Double oct;
     private Double nov;
     private Double dec;
     private Double annual;
     private String potential;

    public SolarRadiationLatilt() {
    }

	
    public SolarRadiationLatilt(long id) {
        this.id = id;
    }
    public SolarRadiationLatilt(long id, Geometry geom, Long gridcode, Double jan, Double feb, Double mar, Double apr, Double may, Double jun, Double jul, Double aug, Double sep, Double oct, Double nov, Double dec, Double annual, String potential) {
       this.id = id;
       this.geom = geom;
       this.gridcode = gridcode;
       this.jan = jan;
       this.feb = feb;
       this.mar = mar;
       this.apr = apr;
       this.may = may;
       this.jun = jun;
       this.jul = jul;
       this.aug = aug;
       this.sep = sep;
       this.oct = oct;
       this.nov = nov;
       this.dec = dec;
       this.annual = annual;
       this.potential = potential;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="geom")
    public Geometry getGeom() {
        return this.geom;
    }
    
    public void setGeom(Geometry geom) {
        this.geom = geom;
    }

    
    @Column(name="gridcode")
    public Long getGridcode() {
        return this.gridcode;
    }
    
    public void setGridcode(Long gridcode) {
        this.gridcode = gridcode;
    }

    
    @Column(name="jan", precision=17, scale=17)
    public Double getJan() {
        return this.jan;
    }
    
    public void setJan(Double jan) {
        this.jan = jan;
    }

    
    @Column(name="feb", precision=17, scale=17)
    public Double getFeb() {
        return this.feb;
    }
    
    public void setFeb(Double feb) {
        this.feb = feb;
    }

    
    @Column(name="mar", precision=17, scale=17)
    public Double getMar() {
        return this.mar;
    }
    
    public void setMar(Double mar) {
        this.mar = mar;
    }

    
    @Column(name="apr", precision=17, scale=17)
    public Double getApr() {
        return this.apr;
    }
    
    public void setApr(Double apr) {
        this.apr = apr;
    }

    
    @Column(name="may", precision=17, scale=17)
    public Double getMay() {
        return this.may;
    }
    
    public void setMay(Double may) {
        this.may = may;
    }

    
    @Column(name="jun", precision=17, scale=17)
    public Double getJun() {
        return this.jun;
    }
    
    public void setJun(Double jun) {
        this.jun = jun;
    }

    
    @Column(name="jul", precision=17, scale=17)
    public Double getJul() {
        return this.jul;
    }
    
    public void setJul(Double jul) {
        this.jul = jul;
    }

    
    @Column(name="aug", precision=17, scale=17)
    public Double getAug() {
        return this.aug;
    }
    
    public void setAug(Double aug) {
        this.aug = aug;
    }

    
    @Column(name="sep", precision=17, scale=17)
    public Double getSep() {
        return this.sep;
    }
    
    public void setSep(Double sep) {
        this.sep = sep;
    }

    
    @Column(name="oct", precision=17, scale=17)
    public Double getOct() {
        return this.oct;
    }
    
    public void setOct(Double oct) {
        this.oct = oct;
    }

    
    @Column(name="nov", precision=17, scale=17)
    public Double getNov() {
        return this.nov;
    }
    
    public void setNov(Double nov) {
        this.nov = nov;
    }

    
    @Column(name="dec", precision=17, scale=17)
    public Double getDec() {
        return this.dec;
    }
    
    public void setDec(Double dec) {
        this.dec = dec;
    }

    
    @Column(name="annual", precision=17, scale=17)
    public Double getAnnual() {
        return this.annual;
    }
    
    public void setAnnual(Double annual) {
        this.annual = annual;
    }

    
    @Column(name="potential", length=12)
    public String getPotential() {
        return this.potential;
    }
    
    public void setPotential(String potential) {
        this.potential = potential;
    }




}


